service:
  name: components-api

plugins:
  - serverless-webpack

provider:
  name: aws
  stage: prod
  region: ap-northeast-2
  runtime: nodejs8.10
  profile: workslow
  environment:
    NODE_ENV: prod

functions:
  get:
    handler: get.default
    events:
      - http:
          method: get
          path: /
          cors: true
  post:
    handler: post.default
    events:
      - http:
          method: post
          path: /
          cors: true
  put:
    handler: put.default
    events:
      - http:
          method: put
          path: /{id}
          cors: true
          request:
            parameters:
              paths:
                id: true
  delete:
    handler: delete.default
    events:
      - http:
          method: delete
          path: /{id}
          cors: true
          request:
            parameters:
              paths:
                id: true
