service:
  name: files-api

plugins:
  - serverless-webpack

provider:
  name: aws
  stage: prod
  region: ap-northeast-2
  runtime: nodejs8.10
  profile: workslow
  environment:
    NODE_ENV: prod

functions:
  get:
    handler: getWithId.default
    events:
      - http:
          method: get
          path: /{id}
          cors: true
          request:
            parameters:
              paths:
                id: true
  post:
    handler: post.default
    events:
      - http:
          method: post
          path: /
          cors: true
